version: '3.6'
services:
  postgres:
    image: postgres:12
    env_file:
      - ./.env
    build:
      context: ./db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
volumes:
  db_data:
