version: '3.6'
services:
  postgres:
    container_name: postgres-moz
    image: postgres:12
    env_file:
      - ./.env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  hasura:
    container_name: hasura-moz
    env_file:
      - ./.env
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
volumes:
  db_data:
