
create schema "flat";

CREATE TABLE "flat"."blockchains"("network_id" varchar NOT NULL, "name" varchar NOT NULL, "logo_url" varchar NOT NULL, "is_synced" boolean, "website" varchar NOT NULL, "is_mainnet" boolean NOT NULL, PRIMARY KEY ("network_id") );

CREATE TABLE "flat"."timeframes"("timeframe_in_hours" integer NOT NULL, PRIMARY KEY ("timeframe_in_hours") );

CREATE TABLE "flat"."blockchain_relations"("blockchain_source" varchar NOT NULL, "blockchain_target" varchar NOT NULL, "is_mainnet" boolean NOT NULL, "timeframe" integer NOT NULL, "ibc_transfers" integer NOT NULL, "ibc_transfers_diff" integer NOT NULL, "ibc_transfers_pending" integer NOT NULL, "ibc_transfers_failed" integer NOT NULL, "ibc_cashflow" bigint NOT NULL, "ibc_cashflow_diff" bigint NOT NULL, "ibc_cashflow_pending" bigint NOT NULL, "source_to_target_ibc_transfers" integer NOT NULL, "source_to_target_ibc_cashflow" bigint NOT NULL, "target_to_source_ibc_transfers" integer NOT NULL, "target_to_source_ibc_cashflow" bigint NOT NULL, PRIMARY KEY ("blockchain_source","blockchain_target","is_mainnet","timeframe") , FOREIGN KEY ("blockchain_source") REFERENCES "flat"."blockchains"("network_id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("blockchain_target") REFERENCES "flat"."blockchains"("network_id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("timeframe") REFERENCES "flat"."timeframes"("timeframe_in_hours") ON UPDATE restrict ON DELETE restrict);

CREATE TABLE "flat"."blockchain_stats"("blockchain" varchar NOT NULL, "timeframe" integer NOT NULL, "txs" integer NOT NULL, "txs_diff" integer NOT NULL, PRIMARY KEY ("blockchain","timeframe") , FOREIGN KEY ("blockchain") REFERENCES "flat"."blockchains"("network_id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("timeframe") REFERENCES "flat"."timeframes"("timeframe_in_hours") ON UPDATE restrict ON DELETE restrict);

CREATE TABLE "flat"."blockchain_switched_stats"("blockchain" varchar NOT NULL, "is_mainnet" boolean NOT NULL, "timeframe" integer NOT NULL, "channels_cnt" integer NOT NULL, "ibc_peers" integer NOT NULL, "txs_rating" integer NOT NULL, "txs_rating_diff" integer NOT NULL, "txs_weight" numeric NOT NULL, "ibc_active_addresses_cnt" integer NOT NULL, "ibc_active_addresses_cnt_diff" integer NOT NULL, "ibc_active_addresses_cnt_rating" integer NOT NULL, "ibc_active_addresses_cnt_rating_diff" integer NOT NULL, "ibc_active_addresses_cnt_weight" numeric NOT NULL, "ibc_cashflow" bigint NOT NULL, "ibc_cashflow_diff" bigint NOT NULL, "ibc_cashflow_rating" integer NOT NULL, "ibc_cashflow_rating_diff" integer NOT NULL, "ibc_cashflow_weight" numeric NOT NULL, "ibc_cashflow_pending" bigint NOT NULL, "ibc_cashflow_in" bigint NOT NULL, "ibc_cashflow_in_diff" bigint NOT NULL, "ibc_cashflow_in_rating" integer NOT NULL, "ibc_cashflow_in_rating_diff" integer NOT NULL, "ibc_cashflow_in_weight" numeric NOT NULL, "ibc_cashflow_in_percent" numeric NOT NULL, "ibc_cashflow_in_pending" bigint NOT NULL, "ibc_cashflow_out" bigint NOT NULL, "ibc_cashflow_out_diff" bigint NOT NULL, "ibc_cashflow_out_rating" integer NOT NULL, "ibc_cashflow_out_rating_diff" integer NOT NULL, "ibc_cashflow_out_weight" numeric NOT NULL, "ibc_cashflow_out_percent" numeric NOT NULL, "ibc_cashflow_out_pending" bigint NOT NULL, "ibc_transfers" integer NOT NULL, "ibc_transfers_diff" integer NOT NULL, "ibc_transfers_rating" integer NOT NULL, "ibc_transfers_rating_diff" integer NOT NULL, "ibc_transfers_weight" numeric NOT NULL, "ibc_transfers_pending" integer NOT NULL, "ibc_transfers_success_rate" numeric NOT NULL, PRIMARY KEY ("blockchain","is_mainnet","timeframe") , FOREIGN KEY ("blockchain") REFERENCES "flat"."blockchains"("network_id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("timeframe") REFERENCES "flat"."timeframes"("timeframe_in_hours") ON UPDATE restrict ON DELETE restrict);

CREATE TABLE "flat"."channels_stats"("blockchain" varchar NOT NULL, "timeframe" integer NOT NULL, "channel_id" varchar NOT NULL, "client_id" varchar NOT NULL, "connection_id" varchar NOT NULL, "is_channel_open" boolean NOT NULL, "counterparty_blockchain" varchar NOT NULL, "counterparty_channel_id" varchar NOT NULL, "ibc_transfers" integer NOT NULL, "ibc_transfers_diff" integer NOT NULL, "ibc_transfers_pending" integer NOT NULL, "ibc_transfers_failed" integer NOT NULL, "ibc_transfers_failed_diff" integer NOT NULL, "ibc_transfers_success_rate" numeric NOT NULL, "ibc_transfers_success_rate_diff" numeric NOT NULL, "ibc_cashflow_in" bigint NOT NULL, "ibc_cashflow_in_diff" bigint NOT NULL, "ibc_cashflow_in_pending" bigint NOT NULL, "ibc_cashflow_out" bigint NOT NULL, "ibc_cashflow_out_diff" bigint NOT NULL, "ibc_cashflow_out_pending" bigint NOT NULL, PRIMARY KEY ("blockchain","timeframe","channel_id") , FOREIGN KEY ("blockchain") REFERENCES "flat"."blockchains"("network_id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("timeframe") REFERENCES "flat"."timeframes"("timeframe_in_hours") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("counterparty_blockchain") REFERENCES "flat"."blockchains"("network_id") ON UPDATE restrict ON DELETE restrict);

CREATE TABLE "flat"."total_tf_switched_chart_type"("chart_type" varchar NOT NULL, PRIMARY KEY ("chart_type") );

CREATE TABLE "flat"."total_tf_switched_charts"("is_mainnet" boolean NOT NULL, "timeframe" integer NOT NULL, "chart_type" varchar NOT NULL, "point_index" integer NOT NULL, "point_value" numeric NOT NULL, PRIMARY KEY ("is_mainnet","timeframe","chart_type","point_index") , FOREIGN KEY ("timeframe") REFERENCES "flat"."timeframes"("timeframe_in_hours") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("chart_type") REFERENCES "flat"."total_tf_switched_chart_type"("chart_type") ON UPDATE restrict ON DELETE restrict);

CREATE TABLE "flat"."blockchain_tf_chart_type"("chart_type" varchar NOT NULL, PRIMARY KEY ("chart_type") );

CREATE TABLE "flat"."blockchain_tf_charts"("blockchain" varchar NOT NULL, "timeframe" integer NOT NULL, "chart_type" varchar NOT NULL, "point_index" integer NOT NULL, "point_value" numeric NOT NULL, PRIMARY KEY ("blockchain","timeframe","chart_type","point_index") , FOREIGN KEY ("chart_type") REFERENCES "flat"."blockchain_tf_chart_type"("chart_type") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("blockchain", "timeframe") REFERENCES "flat"."blockchain_stats"("blockchain", "timeframe") ON UPDATE restrict ON DELETE restrict);

CREATE TABLE "flat"."blockchain_tf_switched_chart_type"("chart_type" varchar NOT NULL, PRIMARY KEY ("chart_type") );

CREATE TABLE "flat"."blockchain_tf_switched_charts"("blockchain" varchar NOT NULL, "is_mainnet" boolean NOT NULL, "timeframe" integer NOT NULL, "chart_type" varchar NOT NULL, "point_index" integer NOT NULL, "point_value" numeric NOT NULL, PRIMARY KEY ("blockchain","is_mainnet","timeframe","chart_type","point_index") , FOREIGN KEY ("chart_type") REFERENCES "flat"."blockchain_tf_switched_chart_type"("chart_type") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("blockchain", "is_mainnet", "timeframe") REFERENCES "flat"."blockchain_switched_stats"("blockchain", "is_mainnet", "timeframe") ON UPDATE restrict ON DELETE restrict);
