CREATE TYPE public.temp_t_full_stats_for_each as (
    zone character varying,
    total_txs integer,
    total_ibc_txs integer,
    ibc_percent numeric,
    ibc_tx_out integer,
    ibc_tx_in integer,
    channels_num integer,
    chart json,
    total_txs_rating integer,
    total_txs_diff integer,
    total_txs_rating_diff integer,
    total_ibc_txs_rating integer,
    total_ibc_txs_diff integer,
    total_ibc_txs_rating_diff integer,
    ibc_tx_in_rating integer,
    ibc_tx_in_diff integer,
    ibc_tx_in_rating_diff integer,
    ibc_tx_out_rating integer,
    ibc_tx_out_diff integer,
    ibc_tx_out_rating_diff integer,
    total_ibc_txs_weight numeric,
    total_txs_weight numeric,
    ibc_tx_in_weight numeric,
    ibc_tx_out_weight numeric,
	ibc_tx_failed integer,
	ibc_tx_failed_diff integer,
	total_active_addresses integer,
	total_active_addresses_diff integer,
	total_active_addresses_rating integer,
	total_active_addresses_rating_diff integer
);
