name: Docker Images CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: GitHub Action for DigitalOcean - doctl
      # You may pin to the exact commit or the version.
      # uses: digitalocean/action-doctl@7f3a9967e5f7b8f4581cf10e6891535614f36850
      uses: digitalocean/action-doctl@v2.1.0
      with:
        # Version of doctl to install
#         version: # optional, default is latest
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build backend
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build -t ${{ secrets.REGISTRY }}:${{ github.sha }} -t ${{ secrets.REGISTRY }}:latest ./hasura
    - name: Push backend image
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl registry login
        docker push ${{ secrets.REGISTRY }}

    - name: Notify Telegram
      uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.chat }} # user id or channel name secret
        token: ${{ secrets.token }} # token secret
        status: ${{ job.status }} # do not modify this line
